spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQL8Dialect}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}

server:
  port: ${PORT:8080}
  http2:
    enabled: false

app:
  jwtSecret: ${APP_JWT_SECRET:TuClaveSecretaMuySeguraQueDebeTenerAlMenos64Caracteres1234567890!@}
  jwtExpirationInMs: ${APP_JWT_EXPIRATION_IN_MS:86400000}

google:
  ai:
    api:
      key: ${GOOGLE_AI_API_KEY}

logging:
  level:
    com.webapp.comparar: DEBUG

spring.main.lazy-initialization: true